# Generated by Django 4.2.19 on 2025-02-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apiclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiclient',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
