# Generated by Django 4.2.19 on 2025-02-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_create_at_apiclient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
