# Generated by Django 4.2.19 on 2025-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0006_songrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(help_text="Curator's description of the artwork.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='art_images/')),
                ('aws_url', models.URLField(blank=True, help_text='Direct AWS S3 URL for the image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
