# Generated by Django 4.2.19 on 2025-02-23 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0007_art'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={},
        ),
        migrations.RemoveField(
            model_name='art',
            name='aws_url',
        ),
    ]
